# Generated by Django 5.0 on 2024-02-14 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_last_password_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='random_id',
        ),
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
